title: "Linux工匠"
description: "关注运维自动化|Python开发|linux高可用集群|数据库维护|性能提优|系统架构"
show_downloads: "true"
theme: jekyll-theme-cayman
github:
  zip_url: http://www.bbotte.com/
  another_url: http://www.bbotte.com/
  tar_url: https://github.com/bbotte/bbotte.github.io
