version: '2.4'
services:
  db1-com:
    container_name: db1-com
    image: harbor.bbotte.com/devops/mysql-server:0.03
    volumes:
      - /tmp/1:/var/lib/mysql
      - ./1:/etc/mysql
    ports:
      - 3316:3306
      - 3317:3317
    networks:
      iris:
        ipv4_address: 172.17.1.10
    environment:
      MYSQL_ROOT_PASSWORD: "www.bbotte.com"
      MYSQL_INNODB_BUFFER_POOL_SIZE: "128M"
      DATADIR: "/var/lib/mysql"

  db2-com:
    container_name: db2-com
    image: harbor.bbotte.com/devops/mysql-server:0.03
    volumes:
      - /tmp/2:/var/lib/mysql
      - ./2:/etc/mysql
    ports:
      - 3326:3306
      - 3327:3327
    networks:
      iris:
        ipv4_address: 172.17.1.20
    environment:
      MYSQL_ROOT_PASSWORD: "www.bbotte.com"
      MYSQL_INNODB_BUFFER_POOL_SIZE: "128M"
      DATADIR: "/var/lib/mysql"
      MYSQL_SERVER_ID: 2

  db3-com:
    container_name: db3-com
    image: harbor.bbotte.com/devops/mysql-server:0.03
    volumes:
      - /tmp/3:/var/lib/mysql
      - ./3:/etc/mysql
    ports:
      - 3336:3306
      - 3337:3337
    networks:
      iris:
        ipv4_address: 172.17.1.30
    environment:
      MYSQL_ROOT_PASSWORD: "www.bbotte.com"
      MYSQL_INNODB_BUFFER_POOL_SIZE: "128M"
      MYSQL_INNODB_THREAD_CONCURRENCY: 2
      DATADIR: "/var/lib/mysql"
      MYSQL_SERVER_ID: 3

networks:
  iris:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.17.1.0/24
