version: '2.4'
services:
  zookeeper-com:
    container_name: zookeeper-com
    image: zookeeper   #zookeeper image: https://github.com/31z4/zookeeper-docker/tree/master/3.5.6
    ports:
     - 2181:2181
    networks:
     - bbotte
    environment:
      ZOO_MY_ID: "1"
      ZOO_SERVERS: "server.1=0.0.0.0:2888:3888;2181 "

  kafka-com:
    container_name: kafka-com
    image: kafka:0.1
    ports:
     - 9092:9092
     - 9094:9094
    networks:
     - bbotte
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-com:2181"
      KAFKA_ADVERTISED_HOST_NAME: "192.168.0.118"  # host ip

networks:
  bbotte:
    external: false

